name: CI

on:
  push:
    branches: [main, testing]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Black
        run: black --check .
      - name: Isort
        run: isort --check-only .
      - name: Flake8
        run: flake8 --max-line-length=120 .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Mypy
        run: mypy src tests

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Verify board scaffolding
        run: |
          pytest -o addopts='' tests/test_board_manager.py -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_board_init -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_board_init_custom_path -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_board_init_arg_cache -q
          pytest -o addopts='' tests/test_github_device_flow.py -q
          pytest -o addopts='' tests/test_cli_auth.py::test_cmd_auth_login_oauth -q
          pytest -o addopts='' tests/test_cli_main_oauth.py -q
          pytest -o addopts='' tests/test_slack_oauth.py -q
          pytest -o addopts='' tests/test_cli_slack.py::test_cmd_slack_test -q
          pytest -o addopts='' tests/test_cli_slack.py::test_cmd_slack_notify -q
          pytest -o addopts='' tests/test_slack_bot.py -q
          pytest -o addopts='' tests/test_slack_commands.py -q
          pytest -o addopts='' tests/test_slack_notifications.py -q
          pytest -o addopts='' tests/test_scaffold.py -q
          pytest -o addopts='' tests/test_board_priority.py -q
          pytest -o addopts='' tests/test_installation.py -q
          pytest -o addopts='' tests/test_distribution.py -q
          pytest -o addopts='' tests/test_no_mcp_references.py -q
          pytest -o addopts='' tests/test_token_storage.py -q
          pytest -o addopts='' tests/test_backlog_doctor.py -q
          pytest -o addopts='' tests/test_audit.py -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_audit_and_undo -q
          pytest -o addopts='' tests/test_pinned_items.py -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_pin_unpin_and_list -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_next -q
          pytest -o addopts='' tests/test_cli_commands.py::test_cmd_next_none -q
          pytest -o addopts='' tests/test_api_server.py -q
          pytest -o addopts='' tests/test_ranking_engine.py -q
          pytest -o addopts='' tests/test_planning_workflow.py -q
          pytest -o addopts='' tests/test_openrouter.py -q
          pytest -o addopts='' tests/test_cli_planning.py -q
          pytest -o addopts='' tests/test_cli_extra_planning.py -q
          pytest -o addopts='' tests/test_mem0_client.py -q
          pytest -o addopts='' tests/test_tool_registry.py -q
          pytest -o addopts='' tests/test_hierarchy_manager.py -q
          pytest -o addopts='' tests/test_metrics.py -q
          pytest -o addopts='' tests/test_release_scripts.py -q

