name: CI

on:
  push:
    branches: [main, testing]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Black
        run: black --check .
      - name: Isort
        run: isort --check-only .
      - name: Flake8
        run: flake8 --max-line-length=120 .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Mypy
        run: mypy src tests

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

  integration:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Run integration tests
        run: |
          # Core functionality tests
          pytest tests/test_board_manager.py -q
          pytest tests/test_cli_commands.py -q
          pytest tests/test_github_device_flow.py -q
          pytest tests/test_cli_auth.py -q
          pytest tests/test_cli_main_oauth.py -q
          
          # Slack integration tests
          pytest tests/test_slack_oauth.py -q
          pytest tests/test_cli_slack.py -q
          pytest tests/test_slack_bot.py -q
          pytest tests/test_slack_commands.py -q
          pytest tests/test_slack_notifications.py -q
          
          # Planning and workflow tests
          pytest tests/test_planning_workflow.py -q
          pytest tests/test_cli_planning.py -q
          pytest tests/test_cli_extra_planning.py -q
          pytest tests/test_openrouter.py -q
          
          # Core system tests
          pytest tests/test_ranking_engine.py -q
          pytest tests/test_metrics.py -q
          pytest tests/test_hierarchy_manager.py -q
          pytest tests/test_mem0_client.py -q
          pytest tests/test_tool_registry.py -q
          
          # Installation and distribution tests
          pytest tests/test_installation.py -q
          pytest tests/test_distribution.py -q
          pytest tests/test_documentation.py -q

